<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyTitle>Extensions library that adds several additional methods to existing common types, allowing for extended functionality. This library is part of Mondongo Dehesa Framework.</AssemblyTitle>
    <Description>$(AssemblyTitle)</Description>
    <PackageId>Mondongo.Iberico.Extensions</PackageId>
    <PackageTags>oscarnet mondongo dehesa framework iberico extensions</PackageTags>
    <Title>Mondongo Iberico Extensions (part of Mondongo Dehesa Framework)</Title>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mondongo.Iberico.Extensions.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\ExtensionsResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ExtensionsResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ExtensionsResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ExtensionsResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
