//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mondongo.Iberico.IO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IOResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IOResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mondongo.Iberico.IO.Resources.IOResources", typeof(IOResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path is not valid (&apos;{0}&apos;)..
        /// </summary>
        internal static string PathIsNotValid {
            get {
                return ResourceManager.GetString("PathIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temporary folder has already been deleted previously by another process or user..
        /// </summary>
        internal static string TemporaryDirectoryHasAlreadyBeenDeleted {
            get {
                return ResourceManager.GetString("TemporaryDirectoryHasAlreadyBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subfolders and files contained in the temporary folder (&apos;{0}&apos;) could not be deleted. {1}.
        /// </summary>
        internal static string TemporaryFolderCouldNotBeClear {
            get {
                return ResourceManager.GetString("TemporaryFolderCouldNotBeClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create file in temporary folder (&apos;{0}&apos;). {1}.
        /// </summary>
        internal static string TemporaryFolderFileCouldNotBeCreate {
            get {
                return ResourceManager.GetString("TemporaryFolderFileCouldNotBeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temporary folder instance has been disposed..
        /// </summary>
        internal static string TemporaryFolderHasBeenDisposed {
            get {
                return ResourceManager.GetString("TemporaryFolderHasBeenDisposed", resourceCulture);
            }
        }
    }
}
