<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
          Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <Configurations>Debug;Release</Configurations>
    <DebugSymbols>true</DebugSymbols>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GeneratedAssemblyInfoFile>Properties/QuercusInfo.cs</GeneratedAssemblyInfoFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSource>false</IncludeSource>
    <IncludeSymbols>false</IncludeSymbols>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugType>portable</DebugType>
    <DefineConstants>TRACE;DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>embedded</DebugType>
    <DefineConstants>TRACE;RELEASE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

</Project>